### ISSUE TITLE
Language select, drop-down on hover

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#109]
It may be possible to open the language select menu when a user hovers. Determine if this is useful, desirable, and practical. Implement the auto-dropdown feature if it genuinely improves usability and is practical to add.

**Comment by leosa83** [comment]
@miladf @Davito163 
Whats your input?

**Comment by miladf** [comment]
It truely is more user friendly, but we should be consistent so that it goes good with the buttons next to the language button. Hoover + dropdown is nice, but I personally think it is a bit old way of working. @Davito163 might want to have some kind of overlay as with the share-button interaction. I let him decide :)
