### ISSUE TITLE
Convert Add Project form to multi-page wizard

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#27]
The Add Project is somewhat long, and may be confusing or tedious to complete. To help people with this process, it may be advisable to break it into smaller chunks. To this end, we can convert the form into a multi-step 'wizard'.
# Resources
- [forwarder:meteor-wizard](https://github.com/forwarder/meteor-wizard/) - package to convert AutoForms into elegant, multi-step forms

**Comment by leosa83** [comment]
Nice.

**Comment by 2ECC71** [comment]
Example of using forwarder:meteor-wizard with Flowrouter:
https://github.com/bySabi/meteor-wizard-example-with-flowrouter-bootstrap/

**Comment by 2ECC71** [comment]
Hi there. Been spending a couple of hours on this, mostly to get to know my way around the code.
Im pushing a branch named feature-issue27 with a lot of stuff done, and kind of working. But a few major problems:
1. Next button on page 2 of the 3 page wizard only works after page reload. @brylie i saw you had the same problem. Perhaps this is a deal-breaker?
2. Can't get it to accept SimpleSchema objects, like postalAddress.city and links.url. Gives me "Unexpected token"
3. Messes with our folder structure. 
4. This is probably easy: Have do define Project MongoDB variable on client addProject.html page, otherwise it does not show wizard at all.

Probably a few more stuff that i can't remember atm.

**Comment by brylie** [comment]
1. We had to write our own [templates for each step of the wizard](https://github.com/apinf/api-umbrella-dashboard/tree/develop/client/views/api_backends/add-backend-workflow)
2. You may need to quote the schema objects, `"links.url"`
3. the 'wizard' feature would be defined in its own package folder
4. Please describe this more clearly, or link to your error/code
